### ISSUE TITLE
Including multiple versions of the same bundle in a generated feature

### ISSUE THREAD

**Issue by larkery** [ctron/package-drone#57] opened 2015-03-18 18:29 UTC
Hello,

I have a channel with a generated feature containing its bundles - however, the feature only seems to require the first bundle with a given name that is present in the repository, according to whatever ordering is used when displaying (looks like by version number), so the one with the least version.

Would it be possible to amend the feature generator to require all bundles, including different versions, or even to have a policy about what kind of versions to include?

Thanks!

**Comment by ctron** [comment] 2015-03-19 08:02
Actually that should not be. The feature should contain all bundles which are present in the channel. For this to work, these artifacts have to be detected as OSGi bundles, which is done by the OSGi aspect.

Do you have an example?

**Comment by larkery** [comment] 2015-03-19 13:07
I can provide some screenshots of how it looks for me, if that helps:

![screenshot - 190315 - 13 06 10](https://cloud.githubusercontent.com/assets/1721963/6730941/c18bda7c-ce38-11e4-902e-649e1a6b5914.png)
![screenshot - 190315 - 13 06 29](https://cloud.githubusercontent.com/assets/1721963/6730942/c18beec2-ce38-11e4-817d-75396e67730d.png)
![screenshot - 190315 - 13 06 50](https://cloud.githubusercontent.com/assets/1721963/6730943/c18e0a0e-ce38-11e4-835a-01707792521b.png)

You can see there are two versions of uk.org.cse.nhm.bundle.impl (5.1.4.20150318180928430 and 5.1.4.20150318181048057) but only the first is in the generated feature.

**Comment by ctron** [comment] 2015-03-19 13:57
This looks strange indeed. Could you do me a favor and look into the generated `feature.xml`. It could be a bug in the UI.

**Comment by ctron** [comment] 2015-03-19 14:04
Ok, I can reproduce it. And for me the issue is in the UI. The `feature.xml`file looks fine.

**Comment by ctron** [comment] 2015-03-19 14:37
So there is a fix which will be in the next version.

**Comment by larkery** [comment] 2015-03-20 10:42
I find that the feature.xml matches what I see in the UI; at the moment is is this:
```xml
<requires size="4">
  <required name="uk.org.cse.nhm.bundle.impl" namespace="org.eclipse.equinox.p2.iu" range="[5.1.4.20150319180613408,5.1.4.20150319180613408]"/>
  <required name="uk.org.cse.nhm.manual" namespace="org.eclipse.equinox.p2.iu" range="[5.1.4.20150319182156790,5.1.4.20150319182156790]"/>
  <required name="nhm.platform.feature.jar" namespace="org.eclipse.equinox.p2.iu" range="[6.0.0.201503191822,6.0.0.201503191822]">
    <filter>(org.eclipse.update.install.features=true)</filter>
  </required>
  <required name="uk.org.cse.nhm.bundle-api" namespace="org.eclipse.equinox.p2.iu" range="[1.1.0,1.1.0]"/>
</requires>
```
Interestingly the required version of `uk.org.cse.nhm.bundle.impl` has changed to be the result of another deployment that's happened since I last wrote; however it still only has one version in, and there are three in the channel now.

**Comment by ctron** [comment] 2015-03-20 11:45
Hm, this seems even stranger.

Can you select the parent (generator) of this artifact. Showing the details there should be a green "regenerate" button. This should regenerate the child artifacts. Just to check if this makes any difference.

**Comment by larkery** [comment] 2015-03-20 15:19
I have clicked "regenerate" but it still has only the one version of the requirement. Here is a bit more about how it all fits together, which might help

* The bundle is being created and deployed by maven, using maven-bundle-plugin to package it
* The maven group/artifact/version for it is not the same as the bundle symbolicname or version (not sure if this would cause a problem). The GAV will be something like `uk.org.cse.nhm:clitools:5.1.4-SNAPSHOT` or maybe `uk.org.cse.nhm:clitools:5.1.4-20150319.132310-1` (the latter being the maven build timestamp - don't know how maven repositories really work). The bundle symbolicname is `uk.org.cse.nhm.bundle.impl` and the version has a differently formatted timestamp as the qualifier.

**Comment by ctron** [comment] 2015-03-20 15:27
I am currently in the process of releasing RC1 of 0.5.0, this contains the previously mentioned bug fix.

Maybe you can give it a try. I will take a few minutes though until it is uploaded.

**Comment by larkery** [comment] 2015-03-20 15:51
OK, I will see how that works out, thanks

**Comment by ctron** [comment] 2015-03-23 16:46
0.5.0 is released

**Closed by ctron** 2015-03-23 16:46 UTC
Labels: bug
