### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by afischer211** [ctron/package-drone#112] opened 2015-06-22 13:17 UTC
I run sometimes into this error:
`
15:11:22.539 [qtp1996908597-221] WARN  org.eclipse.jetty.server.HttpChannel [HttpChannel.java:383] /p2/eclipse/p2.index
java.lang.OutOfMemoryError: GC overhead limit exceeded

My Package-Drone instance runs with JVM-parameter **-Xmx6000m** under **Java8u45**

Do you suggest other values (Xmx or another GC-algorithm) for this?

**Comment by ctron** [comment] 2015-06-22 13:35
I think this is a bug as well. My colleague just ran into the same problem.

**Comment by ctron** [comment] 2015-06-22 14:13
Ok, the more information you have on this one the better. We are experience this here as well. But interestingly not in the stress test.

**Comment by afischer211** [comment] 2015-06-22 14:23
I run into the problem after deploying artifacts with maven-deploy-plugin, may be as result of issue #111 (many open postgresql-processes with running queries on maven-deployment).
My channels are filled with OSGi-bundles and features. I use package-drone only as P2-repository, no yum, no maven,... (for this I have a Nexus OSS).
What do you want to know additionally (OS=CentOS7 64Bit, Java8u45, Database=PostgreSQL)?

**Comment by afischer211** [comment] 2015-06-22 14:32
The files from the two most filled channels (where also the most deployment traffic is located) are:
1. channel:
artifacts.xml -> 187KB
content.xml -> 1906 KB
2. channel:
artifacts.xml -> 324KB
content.xml -> 1749KB

**Comment by ctron** [comment] 2015-06-22 14:35
So do you have this with m2? Or with a more recent milestone?

**Comment by afischer211** [comment] 2015-06-22 14:42
Now with m2, because of deadlock-problem with m3 (#108) and deployment-error with m4 (#110) (I tried this m4-version today in the morning).

**Comment by ctron** [comment] 2015-06-22 15:44
After doing several tests and memory dumps .. it looks like this is caused by: https://bugs.eclipse.org/bugs/show_bug.cgi?id=410870

**Comment by ctron** [comment] 2015-06-22 16:23
Although it seemed that issue it actually was another one. [Bug 289771](https://bugs.eclipse.org/bugs/show_bug.cgi?id=289771), reported in 2009 is the key. And the workaround seems to actually fix it.

**Comment by afischer211** [comment] 2015-06-22 16:24
So I can hope for a soon fix inside package-drone?

**Comment by ctron** [comment] 2015-06-22 16:26
Yes.

**Comment by ctron** [comment] 2015-06-22 16:45
I just dropped you the release file to the same wuala folder. I will take a few minutes until it is uploaded. Unfortunately I have to leave now, so I cannot complete the release today or check if the Wuala upload was successful. But maybe it helps you!

**Comment by afischer211** [comment] 2015-06-22 16:46
Thanks! I will check the wuala folder and try the new build.

**Comment by afischer211** [comment] 2015-06-22 17:42
If have downloaded and installed the m5 version. I get some exceptions on startup, but in general it seems to run better than m2.
I will look further...

**Comment by ctron** [comment] 2015-06-23 09:45
So this one should be fixed. Please re-open otherwise.

**Closed by ctron** 2015-06-23 09:45 UTC
Labels: bug
