### ISSUE TITLE
Performance drops when channel contains more than 10k bundles

### ISSUE THREAD

**Issue by SvenEwald** [ctron/package-drone#132] opened 2015-09-04 05:29 UTC
While mirroring the Bundles of the Eclipse Babel project (30k small Bundles), performance of upload drops down to a few seconds/bundle. GUI is not useable any more due to missing paging.

Current workaround is to split channel for languages.

**Comment by SvenEwald** [comment] 2015-09-04 05:40
CPU load is high (220%), Memory usage is low (30%)

**Comment by ctron** [comment] 2015-09-21 08:23
Sorry for the long delay.

So the problem is more in the UI? Do you have a simple way on how to import babel? In order to reproduce this issue.

**Comment by ctron** [comment] 2015-10-09 13:36
Ok I just uploaded the babel P2 repository with the current master:

105577 bundles and features -> 198933 ms for the upload process

10313 ms for rendering the web page itself

Still the browser has some issues executing the JavaScript when using the tree mode.

However adding another bundle afterwards costs 55420 ms.

**Comment by ctron** [comment] 2015-10-09 15:01
The main time when adding another artifact is spent by pulling together the p2 repository files.

The current process needs to spool out the blob, parse the XML, add it to the final DOM tree. And has to do it four times (artifacts & metadata, compressed and uncompressed).

One improvement could be to prepare the XML fragment and store it in the metadata. That way the final process, which is run every time the channel is modified, only needs to stitch strings together.

However this would not work with Tycho in the same channel. Since Tycho still creates its own p2 fragments.

Also do we need to know the number of units/artifacts before actually adding them. P2's data format puts the number of elements in the outer XML element. And each p2 fragment can contain multiple units.

**Comment by ctron** [comment] 2015-10-09 15:06
On top of that, could the p2 artifacts fragment contain an artifact twice, with a different md5 sum. This is detected by the validator and the artifact is left out of the final result. But only to one artifact, not the full fragment.

**Comment by afischer211** [comment] 2015-11-19 13:25
With current version **0.11.3** I have no more performance-problems with channels with more than 13000 artifacts inside (but big problems with older version **0.10.4**).

**Comment by ctron** [comment] 2015-11-19 13:37
So with 0.11.x in mind, this sounds good?!

**Comment by afischer211** [comment] 2015-11-19 13:50
Yes, the performance-improvement of 0.11.x was awesome!

**Comment by ctron** [comment] 2015-11-19 13:57
So maybe it is time to close this issue then. And open the next one for 100k :wink:

**Comment by afischer211** [comment] 2015-11-19 14:12
I'm not the reporter of this issue. But may be you can close this issue based on my answers?

**Comment by ctron** [comment] 2015-11-19 14:36
True. Sorry, I overlooked that.

**Closed by ctron** 2015-11-19 14:36 UTC
Labels: bug, enhancement, help wanted
